name: learning
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-216.1.beta

# Add regular dependencies here.
dependencies:
  date_format: ^2.0.9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
